# Generated by Django 2.2.5 on 2020-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('age', models.IntegerField(default=23, verbose_name='年龄')),
                ('tel', models.CharField(max_length=11, null=True, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户信息表',
                'db_table': 'user_message',
            },
        ),
    ]
